CREATE DATABASE LoginChat
USE LoginChat;

CREATE TABLE Login(
	KEYLOGIN VARCHAR(50) PRIMARY KEY NOT NULL
)

INSERT INTO Login(KEYLOGIN) VALUES ('admin')
INSERT INTO Login(KEYLOGIN) VALUES ('abc123')
INSERT INTO Login(KEYLOGIN) VALUES ('def456')
INSERT INTO Login(KEYLOGIN) VALUES ('qwe321')
INSERT INTO Login(KEYLOGIN) VALUES ('asd098')
INSERT INTO Login(KEYLOGIN) VALUES ('zxc243')
INSERT INTO Login(KEYLOGIN) VALUES ('765uio')
INSERT INTO Login(KEYLOGIN) VALUES ('bnm890')
INSERT INTO Login(KEYLOGIN) VALUES ('jkl678')
INSERT INTO Login(KEYLOGIN) VALUES ('tyu567')
INSERT INTO Login(KEYLOGIN) VALUES ('234fgh')
INSERT INTO Login(KEYLOGIN) VALUES ('987poi')
INSERT INTO Login(KEYLOGIN) VALUES ('hjk654')
INSERT INTO Login(KEYLOGIN) VALUES ('rty432')
INSERT INTO Login(KEYLOGIN) VALUES ('345hfds')