CREATE DATABASE LOGINDATABASE
USE LOGINDATABASE;

CREATE TABLE KEYLOGIN(
KEYLOGIN VARCHAR(20) PRIMARY KEY NOT NULL
)

INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('admin')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('abc123gre')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('def456luc')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('qwe321gar')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('asd098dec')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('zxc243cha')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('765uiorai')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('bnm890meo')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('jkl678ser')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('tyu567sce')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('234fghtal')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('987poicor')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('hjk654dra')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('rty432inf')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('345hfdint')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('azq632yoi')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('dkf835fur')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('jht349yun')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('lao876keq')
INSERT INTO KEYLOGIN(KEYLOGIN) VALUES ('noi569eul')